export const PROVINCE_DATA_REQUEST = "PROVINCE_DATA_REQUEST";
export const PROVINCE_DATA_SUCCESS = "PROVINCE_DATA_SUCCESS";
export const PROVINCE_DATA_FAIL = "PROVINCE_DATA_FAIL";
export const PROVINCE_DATA_RESET = "PROVINCE_DATA_RESET ";

export const DISTRICT_DATA_REQUEST = "DISTRICT_DATA_REQUEST";
export const DISTRICT_DATA_SUCCESS = "DISTRICT_DATA_SUCCESS";
export const DISTRICT_DATA_FAIL = "DISTRICT_DATA_FAIL";
export const DISTRICT_DATA_RESET = "DISTRICT_DATA_RESET";

export const WARD_DATA_REQUEST = "WARD_DATA_REQUEST";
export const WARD_DATA_SUCCESS = "WARD_DATA_SUCCESS";
export const WARD_DATA_FAIL = "WARD_DATA_FAIL";
export const WARD_DATA_RESET = "WARD_DATA_RESET";
